version: '3.3'
services:
  redis:
    container_name: redis
    command: redis-server
    build:
      context: .
      dockerfile: docker/Dockerfile-Redis
    expose:
      - 6379
    ports:
      - 6379:6379